IO.puts ["Sum: ", to_string(Stats.sum([1,2,3,4]))]
IO.puts ["Average: ", to_string(Stats.avg([1,2,3,4]))]
IO.puts ["Min: ", to_string(Stats.min([1,2,3,4]))]
IO.puts ["Max: ", to_string(Stats.max([1,2,3,4]))]
IO.puts ["Range: ", to_string(Stats.range([1,2,3,4]))]
